config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "registrations#new"

  # get "home", to: "homepage#index"
  
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "login#new"
  post "sign_in", to: "login#create"
  post "logout", to: "login#logout"

  get "add_tour", to: "tours#new"
  get "tours", to: "tours#showAllTour"
  get "chosen_tour", to: "tours#showTour"
  post "add_tour", to: "tours#create"
  post "tours_with_companion", to: "tours#bookTicketWithCompanion"
  post "tours_without_companion", to: "tours#bookTicketWithoutCompanion"
  
  
  get "tickets", to: "tickets#showUserTickets"
  get "all_tickets", to: "tickets#showAllTickets"
  post "cancel", to: "tickets#cancelTicket"

  get "admin", to: "admin#new"
  post "admin", to: "admin#create"
  post "logout_admin", to: "admin#logout"

end

app/models/ticket.rb
class Ticket < ApplicationRecord
    belongs_to :user
    belongs_to :tour


    def cancelTicket
        
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
    before_action :checkUser

    def checkUser
        if session[:user_id].present?
            if User.exists?session[:user_id]
                @user = User.find(session[:user_id])
            else
                redirect_to sign_up_path, notice: "Login Please"
            end
        else
            redirect_to sign_up_path, notice: "Logged Out"
        end
    end

    def showUserTickets 
        @tickets = @user.tickets
    end

    def showAllTickets
        @all_tickets = Ticket.all
    end

    def cancelTicket
        ticket_to_cancel = Ticket.find(params[:param])
        user = ticket_to_cancel.user
        tour = ticket_to_cancel.tour

        #Call to model cancelTicket

        if ticket_to_cancel.companion_user_name.present?
            available_companion = tour.companions.find_by(gender:user.gender)

            companion_ticket = Ticket.find_by(user_id: User.find_by(user_name: ticket_to_cancel.companion_user_name).id, tour_id: tour.id)

            if available_companion.present?
                available_companion_ticket = Ticket.find(available_companion.ticket_id)
                available_companion_ticket.companion_user_name = ticket_to_cancel.companion_user_name
                available_companion_ticket.save

                companion_ticket.companion_user_name = available_companion.user.user_name
                companion_ticket.save

                available_companion.delete
            else
                companion_ticket.companion_user_name = nil
                companion_ticket.save

                companion_to_add = Companion.new
                companion_to_add.gender = user.gender
                companion_to_add.tour_id = tour.id
                companion_to_add.user_id = companion_ticket.user.id
                companion_to_add.ticket_id = companion_ticket.id
                companion_to_add.save
            end
        else
            available_companion = tour.companions.find_by(gender:user.gender)
            if available_companion.present?
                if available_companion.user.eql?(user)
                    available_companion.delete
                end                
            end
        end
        ticket_to_cancel.delete
        tour.passenger_limit = tour.passenger_limit + 1
        tour.save
        flash[:success] = "Successfully Cancelled Ticket for " + tour.tour_code.to_s
        redirect_to tickets_path
    end
end

app/views/tickets/showAllTickets.html.erb
<%= render partial: "shared/navbar" %>
<div class="ms-5 mt-5 me-5">
  <h1> All Tickets </h1>

  <table class="table table-striped">
    <tr>
      <th>Ticket Code</th>
      <th>From </th>
      <th>To </th>
      <th>Tour Code</th>
      <th>User Name </th>
      <th>Gender</th>
      <th>Companion User Name</th>
    </tr>

  <% @all_tickets.each do |ticket| %>
    <tr>
      <td><%= ticket.id %></td>
      <td><%= ticket.tour.from %></td>
      <td><%= ticket.tour.to %></td>
      <td><%= ticket.tour.tour_code %></td>
      <td><%= ticket.user.user_name%></td>
      <td><%= ticket.user.gender.eql?("m") ? "Male": "Female" %></td>
      <td><%= ticket.companion_user_name %></td>
      </tr>
  <% end %>
  </table>
</div>

app/views/tickets/showUserTickets.html.erb
<%= render partial: "shared/navbar"%>
<div class="text-center">
      <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: 'alert alert-info' %>
      <% end %>
</div>
<div class="ms-5 mt-5 me-5">
  <h1> My Tickets </h1>

  <table class="table table-striped">
    <tr>
      <th>Ticket Code</th>
      <th>From </th>
      <th>To </th>
      <th>Date </th>
      <th>Tour Code</th>
      <th>Companion User Name</th>
      <th>Cancel</th>
    </tr>

  <% @tickets.each do |ticket| %>
    <tr>
      <td><%= ticket.id %></td>
      <td><%= ticket.tour.from %></td>
      <td><%= ticket.tour.to %></td>
      <td><%= ticket.tour.date.strftime('%A, %d/%m/%Y') %></td>
      <td><%= ticket.tour.tour_code %></td>
      <td><%= ticket.companion_user_name %></td>
      <td><%= button_to 'Cancel', cancel_path(param:ticket.id), class: "btn btn-danger" %></td>
    </tr>
  <% end %>
  </table>
</div>